# Generated by Django 5.2 on 2025-04-28 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 4, 28, 15, 39, 13, 640437), verbose_name='Опубликовано'),
        ),
    ]
